import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';

type ConstraintSummary = {
  satisfied_soft: Record<string, number>;
  violated_soft: Record<string, number>;
  hard_violations: string[];
};

type Layout = {
  id: string;
  assignments: Record<string, string>;
  score: number;
  objective_breakdown: Record<string, number>;
  variant_label?: string | null;
  variant_id?: string | null;
  summary?: ConstraintSummary;
};

type TotLayout = {
  value: number;
  weights: Record<string, number>;
  notes: string;
  layout: Layout;
};

const demoPayload = {
  guests: [
    { id: 'g1', name: 'Alice', group_id: 'family_a', importance: 2, tags: [], must_sit_with: [], must_not_sit_with: [] },
    { id: 'g2', name: 'Bob', group_id: 'family_a', importance: 1, tags: [], must_sit_with: [], must_not_sit_with: [] },
    { id: 'g3', name: 'Charlie', group_id: 'friends', importance: 0, tags: [], must_sit_with: [], must_not_sit_with: ['g4'] },
    { id: 'g4', name: 'Dana', group_id: 'friends', importance: 0, tags: [], must_sit_with: [], must_not_sit_with: [] }
  ],
  tables: [
    { id: 't1', name: 'Table 1', capacity: 4, zone: null, constraints: {} },
    { id: 't2', name: 'Table 2', capacity: 4, zone: null, constraints: {} }
  ],
  settings: {},
  tot: {
    depth: 2,
    branching: 4,
    n_generate: 4,
    n_evaluate: 4,
    top_k: 3
  }
};

const API_BASE = import.meta.env.VITE_API_BASE || '';

const Recommendations: React.FC = () => {
  const [layouts, setLayouts] = useState<TotLayout[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchLayouts = async () => {
      setLoading(true);
      setError(null);
      try {
        const response = await fetch(`${API_BASE}/api/layouts/generate`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify(demoPayload)
        });

        if (!response.ok) {
          throw new Error(`Server responded with ${response.status}`);
        }

        const data = await response.json();
        setLayouts(data.layouts ?? []);
      } catch (err: any) {
        setError(err.message || 'Failed to fetch layouts');
      } finally {
        setLoading(false);
      }
    };

    fetchLayouts();
  }, []);

  return (
    <div className="flex-grow max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 w-full">
      <div className="text-center mb-16">
        <h1 className="flex items-center justify-center gap-2 font-display text-4xl md:text-5xl text-text-main dark:text-secondary mb-4">
          <span className="material-icons-round text-4xl text-primary">auto_awesome</span> Top ToT Recommendations
        </h1>
        <p className="text-lg text-gray-600 dark:text-gray-400 max-w-2xl mx-auto">
          These seating options are generated by SeatHarmony&apos;s Tree-of-Thoughts search over Gurobi-backed layouts.
        </p>
      </div>

      {loading && (
        <div className="flex justify-center items-center py-16">
          <span className="material-icons-round animate-spin mr-2 text-primary">progress_activity</span>
          <span className="text-gray-600 dark:text-gray-300 text-sm">Requesting ToT layouts from the backend...</span>
        </div>
      )}

      {error && (
        <div className="max-w-xl mx-auto mb-8 p-4 rounded-xl bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 text-sm text-red-700 dark:text-red-200 flex items-start gap-2">
          <span className="material-icons-round text-base mt-0.5">error</span>
          <div>
            <p className="font-semibold mb-1">Couldn&apos;t reach the ToT backend</p>
            <p>{error}</p>
            <p className="mt-2 text-xs text-red-600/80 dark:text-red-200/80">
              Make sure the Python backend (FastAPI/Streamlit) is running and reachable at <code>{API_BASE || window.location.origin}</code>.
            </p>
          </div>
        </div>
      )}

      {!loading && !error && layouts.length === 0 && (
        <div className="text-center text-gray-500 dark:text-gray-400 text-sm">
          No layouts returned yet. Ensure the backend is running with the ToT API enabled.
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 items-start">
        {layouts.map((entry, index) => {
          const { layout, value, weights, notes } = entry;
          const scoreLabel = `${Math.round(layout.score || value)}/100`;
          const titleLabels = ['Option A', 'Option B', 'Option C'];
          const variantLabel = titleLabels[index] || `Option ${index + 1}`;

          return (
            <div
              key={index}
              className="group relative bg-white dark:bg-surface-dark rounded-2xl shadow-soft hover:shadow-glow transition-all duration-300 overflow-hidden border border-secondary/20 dark:border-white/5 transform hover:-translate-y-1 h-full flex flex-col"
            >
              <div className={`absolute top-0 left-0 right-0 h-1.5 ${index === 0 ? 'bg-primary' : index === 1 ? 'bg-secondary' : 'bg-accent'}`}></div>
              <div className="p-8 flex-grow">
                <div className="flex justify-between items-start mb-6">
                  <div className="bg-primary/10 dark:bg-primary/20 p-3 rounded-xl">
                    <span className="material-icons-round text-primary text-2xl">family_restroom</span>
                  </div>
                  <div className="flex items-center gap-1 bg-green-50 dark:bg-green-900/30 px-3 py-1 rounded-full border border-green-100 dark:border-green-800">
                    <span className="text-sm font-bold text-green-700 dark:text-green-300">{scoreLabel}</span>
                    <span className="material-icons-round text-green-600 dark:text-green-400 text-sm">stars</span>
                  </div>
                </div>
                <h2 className="flex items-center gap-2 font-display text-2xl text-text-main dark:text-white mb-2">
                  <span className="material-icons-round">handshake</span> {variantLabel}
                </h2>
                <p className="text-sm text-gray-500 dark:text-gray-400 mb-2 italic">
                  Objective weights: group cohesion {weights.group_cohesion?.toFixed(2) ?? '—'}, conflict avoidance{' '}
                  {weights.conflict_avoidance?.toFixed(2) ?? '—'}, VIP {weights.vip_preference?.toFixed(2) ?? '—'}.
                </p>
                {notes && (
                  <p className="text-xs text-primary dark:text-accent mb-4">
                    Thought that produced this variant: <span className="font-semibold">{notes}</span>
                  </p>
                )}
                <div className="space-y-2 mb-6">
                  <h3 className="text-xs font-bold uppercase tracking-widest text-gray-400 dark:text-gray-500">Assignments</h3>
                  <div className="text-xs max-h-32 overflow-y-auto rounded-lg bg-gray-50 dark:bg-gray-800/60 p-3 border border-gray-100 dark:border-gray-700 space-y-1">
                    {Object.entries(layout.assignments).map(([guestId, tableId]) => (
                      <div key={guestId} className="flex justify-between gap-2">
                        <span className="font-mono text-gray-600 dark:text-gray-300">{guestId}</span>
                        <span className="text-gray-500 dark:text-gray-400">→ {tableId}</span>
                      </div>
                    ))}
                  </div>
                </div>
                {layout.summary && (
                  <div className="space-y-2 mb-4">
                    <h3 className="text-xs font-bold uppercase tracking-widest text-gray-400 dark:text-gray-500">Constraint Summary</h3>
                    <p className="text-xs text-gray-600 dark:text-gray-300">
                      Hard violations: {layout.summary.hard_violations.length || 0}
                    </p>
                  </div>
                )}
              </div>
              <div className="p-6 pt-0 mt-auto">
                <Link
                  to="/planner"
                  className="w-full py-3 px-4 bg-primary hover:bg-[#777b63] text-white rounded-xl font-medium transition-colors shadow-lg shadow-primary/20 flex justify-center items-center gap-2 group-hover:gap-3 transition-all"
                >
                  <span className="material-icons-round text-sm">auto_awesome</span> Select & Refine
                  <span className="material-icons-round text-sm">arrow_forward</span>
                </Link>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default Recommendations;